# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareIdea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userId',
        ),
    ]
