# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-04 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareIdea', '0002_remove_userprofile_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('starred_comment', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ManyToManyField(to='shareIdea.userProfile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
