# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareIdea', '0002_remove_userprofile_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('starred_comment', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='school',
            new_name='department',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualifications',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='statement',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_projects',
            field=models.ManyToManyField(related_name='my_projects', to='shareIdea.Project'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_projects',
            field=models.ManyToManyField(related_name='other_projects', to='shareIdea.Project'),
        ),
    ]
