# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareIdea', '0003_auto_20180606_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='my_projects',
            field=models.ManyToManyField(related_name='project_owner', to='shareIdea.Project'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other_projects',
            field=models.ManyToManyField(related_name='participant', to='shareIdea.Project'),
        ),
    ]
