# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-05 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareIdea', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='school',
            new_name='department',
        ),
        migrations.AddField(
            model_name='project',
            name='participant',
            field=models.ManyToManyField(related_name='userprofile2', to='shareIdea.userProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualifications',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='statement',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ManyToManyField(related_name='userprofile', to='shareIdea.userProfile'),
        ),
    ]
