# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-06 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareIdea', '0004_auto_20180605_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='participant',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_projects',
            field=models.ManyToManyField(related_name='my_projects', to='shareIdea.Project'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_projects',
            field=models.ManyToManyField(related_name='other_projects', to='shareIdea.Project'),
        ),
    ]
